### ISSUE TITLE
More complete documentation

### ISSUE THREAD

**Issue by micmath** [mdp/middlefiddle#1]
It isn't obvious, in my opinion, how to install and use middlefiddle from the current documentation. It would be helpful to have more information added to the README, like how to start the proxy server, how to access a website using the proxy, etc.

**Comment by mdp** [comment]
Agreed, I'm working on rectifying this soon. I'll be getting some more functionality into it, including the ability to quickly launch new proxies from the command line.

**Comment by micmath** [comment]
Thanks. I'll be looking forward to using middlefiddle as it develops.
