### ISSUE TITLE
Middlefiddle starts but hangs on connections

### ISSUE THREAD

**Issue by Fuitad** [mdp/middlefiddle#5]
Running OSX with latest node. Middlefiddle starts but hangs forever on new connections :\

```
$ ./bin/middlefiddle
Loading from /Users/fuitad/Workspace/middlefiddle/.middlefiddle
Loading: default
Loading: ft.com
Loading: github.com
Loading: google.com
Loading: httpbin.org
Loading: snip.it
Loading: soundcloud.com
Starting LiveLogger on 8411
Starting HTTP Proxy on port 8080
```

Any idea?

**Comment by mdp** [comment]
No idea off the top of my head, but I'm working on a big refactor for Node 0.10.x that should clean things up.

I'd recommend using Node 0.8.x until the refactor is finished and out.

**Comment by Fuitad** [comment]
I'll see what version of node I'm using. Maybe it's related. 

Thanks!

**Comment by Fuitad** [comment]
That seemed to be the issue. I was running stable 0.10.4 and it was hanging.

I installed 0.8.23 and middlefiddle is working :)
