### ISSUE TITLE
TypeError: util.pump is not a function when running npm install

### ISSUE THREAD

**Issue by morganchristiansson** [mdp/middlefiddle#7]
```
<prefix>/node_modules/middlefiddle/setup.js:24
      util.pump(original, target);
           ^

TypeError: util.pump is not a function
    at WriteStream.<anonymous> (<prefix>/node_modules/middlefiddle/setup.js:24:12)
    at WriteStream.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (fs.js:2128:10)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by mdp** [comment]
Unfortunately, I've not updated this project in more than 4 years, so I think the Node.js API has long since moved on. The best alternative I've found Charles Web Proxy if you're just wanting to inspect outbound requests.

**Comment by morganchristiansson** [comment]
It's a shame, just been reviewing the different mitm capable https hijacking proxies and this was one of the oldest and best documented ones. It has tests too!

I got past this error but there seemed like the right event handlers not being not being run so one of http and https proxying wasn't working once I got it running after fixing some errors similar to this one. I'm now looking at https://github.com/horaci/node-mitm-proxy/ ... Which just works. No tests tho.

Charles looks nice but this is for use in an automated testsuite so Charles isn't applicable for this usecase..

**Comment by mdp** [comment]
Yeah, unfortunately, I just haven't had the time to keep it up to date.

Another option, but it looks like it's not maintained, is https://github.com/runk/node-thin. And if you're willing to leave Node.js, https://github.com/elazarl/goproxy looks like a really good up to date alternative.

The other option is to run middle fiddle with an older version of Node.js that supports the older API. When I get a free moment, I'll take a look at the new API and see if I can get middle fiddle back up and running.

**Comment by morganchristiansson** [comment]
Getting tests passing should be enough to get most of it working again. And the APIs seem pretty nice all around so hope it's not too hard.

https://github.com/horaci/node-mitm-proxy/ is working OK for me and I haven't needed to to fork the library yet :+1:
