### ISSUE TITLE
when i try to install via `npm -g` it say `util.pump is not a function`

### ISSUE THREAD

**Issue by perymimon** [mdp/middlefiddle#8]
middlefiddle@0.3.3 postinstall /usr/lib/node_modules/middlefiddle
> node setup.js postinstall

Creating .middlefiddle home directory
/usr/lib/node_modules/middlefiddle/setup.js:24
      util.pump(original, target);
           ^

TypeError: util.pump is not a function
    at WriteStream.<anonymous> (/usr/lib/node_modules/middlefiddle/setup.js:24:12)

**Comment by mdp** [comment]
Unfortunately it depends on [Node 0.6.x](https://github.com/mdp/middlefiddle/blob/master/README.md#installation-via-github), which is fairly ancient at this point (~8 years old). I've not had a chance to update the project, but I expect products like [Fiddler](https://www.telerik.com/fiddler) and [Charles Web Debug Proxy](https://www.charlesproxy.com/) problably do a better job at this point.
