### ISSUE TITLE
Why is this project abandoned?

### ISSUE THREAD

**Issue by m-Phoenix852** [mdp/middlefiddle#9]
This is something I would really want to use, but this project has been abandoned for over 10 years. Any updates?

**Comment by mdp** [comment]
No updates on my end, but it's MIT licensed, so you can fork it and update it if you think it's worth the effort, however it's definitely using a very old version of Node. Depending on what you're trying to do you can use proxy's like:

- https://proxyman.io/
- https://www.charlesproxy.com/
